// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roomStatusInfoL.proto

package study.springboot.myspringboot.model.protobuf;

public final class RoomStatusInfoLOuterClass {
  private RoomStatusInfoLOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RoomStatusInfoLOrBuilder extends
      // @@protoc_insertion_point(interface_extends:study.springboot.myspringboot.model.protobuf.RoomStatusInfoL)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo RoomStatusInfoList = 1;</code>
     */
    java.util.List<RoomStatusInfoL.RoomStatusInfo>
        getRoomStatusInfoListList();
    /**
     * <code>repeated .study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo RoomStatusInfoList = 1;</code>
     */
    RoomStatusInfoL.RoomStatusInfo getRoomStatusInfoList(int index);
    /**
     * <code>repeated .study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo RoomStatusInfoList = 1;</code>
     */
    int getRoomStatusInfoListCount();
    /**
     * <code>repeated .study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo RoomStatusInfoList = 1;</code>
     */
    java.util.List<? extends RoomStatusInfoL.RoomStatusInfoOrBuilder>
        getRoomStatusInfoListOrBuilderList();
    /**
     * <code>repeated .study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo RoomStatusInfoList = 1;</code>
     */
    RoomStatusInfoL.RoomStatusInfoOrBuilder getRoomStatusInfoListOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code study.springboot.myspringboot.model.protobuf.RoomStatusInfoL}
   */
  public  static final class RoomStatusInfoL extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:study.springboot.myspringboot.model.protobuf.RoomStatusInfoL)
      RoomStatusInfoLOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RoomStatusInfoL.newBuilder() to construct.
    private RoomStatusInfoL(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RoomStatusInfoL() {
      roomStatusInfoList_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RoomStatusInfoL(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                roomStatusInfoList_ = new java.util.ArrayList<RoomStatusInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              roomStatusInfoList_.add(
                  input.readMessage(RoomStatusInfo.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          roomStatusInfoList_ = java.util.Collections.unmodifiableList(roomStatusInfoList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RoomStatusInfoLOuterClass.internal_static_study_springboot_myspringboot_model_protobuf_RoomStatusInfoL_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RoomStatusInfoLOuterClass.internal_static_study_springboot_myspringboot_model_protobuf_RoomStatusInfoL_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RoomStatusInfoL.class, Builder.class);
    }

    public interface RoomStatusInfoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string HotelMainID = 1;</code>
       */
      String getHotelMainID();
      /**
       * <code>string HotelMainID = 1;</code>
       */
      com.google.protobuf.ByteString
          getHotelMainIDBytes();

      /**
       * <code>string RoomNo = 2;</code>
       */
      String getRoomNo();
      /**
       * <code>string RoomNo = 2;</code>
       */
      com.google.protobuf.ByteString
          getRoomNoBytes();

      /**
       * <code>int32 State = 3;</code>
       */
      int getState();

      /**
       * <code>string CheckIn = 4;</code>
       */
      String getCheckIn();
      /**
       * <code>string CheckIn = 4;</code>
       */
      com.google.protobuf.ByteString
          getCheckInBytes();

      /**
       * <code>string CheckOut = 5;</code>
       */
      String getCheckOut();
      /**
       * <code>string CheckOut = 5;</code>
       */
      com.google.protobuf.ByteString
          getCheckOutBytes();

      /**
       * <code>string CustomerName = 6;</code>
       */
      String getCustomerName();
      /**
       * <code>string CustomerName = 6;</code>
       */
      com.google.protobuf.ByteString
          getCustomerNameBytes();
    }
    /**
     * Protobuf type {@code study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo}
     */
    public  static final class RoomStatusInfo extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo)
        RoomStatusInfoOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use RoomStatusInfo.newBuilder() to construct.
      private RoomStatusInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private RoomStatusInfo() {
        hotelMainID_ = "";
        roomNo_ = "";
        state_ = 0;
        checkIn_ = "";
        checkOut_ = "";
        customerName_ = "";
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private RoomStatusInfo(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                hotelMainID_ = s;
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                roomNo_ = s;
                break;
              }
              case 24: {

                state_ = input.readInt32();
                break;
              }
              case 34: {
                String s = input.readStringRequireUtf8();

                checkIn_ = s;
                break;
              }
              case 42: {
                String s = input.readStringRequireUtf8();

                checkOut_ = s;
                break;
              }
              case 50: {
                String s = input.readStringRequireUtf8();

                customerName_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RoomStatusInfoLOuterClass.internal_static_study_springboot_myspringboot_model_protobuf_RoomStatusInfoL_RoomStatusInfo_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RoomStatusInfoLOuterClass.internal_static_study_springboot_myspringboot_model_protobuf_RoomStatusInfoL_RoomStatusInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RoomStatusInfo.class, Builder.class);
      }

      public static final int HOTELMAINID_FIELD_NUMBER = 1;
      private volatile Object hotelMainID_;
      /**
       * <code>string HotelMainID = 1;</code>
       */
      public String getHotelMainID() {
        Object ref = hotelMainID_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          hotelMainID_ = s;
          return s;
        }
      }
      /**
       * <code>string HotelMainID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHotelMainIDBytes() {
        Object ref = hotelMainID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          hotelMainID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int ROOMNO_FIELD_NUMBER = 2;
      private volatile Object roomNo_;
      /**
       * <code>string RoomNo = 2;</code>
       */
      public String getRoomNo() {
        Object ref = roomNo_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          roomNo_ = s;
          return s;
        }
      }
      /**
       * <code>string RoomNo = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRoomNoBytes() {
        Object ref = roomNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          roomNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int STATE_FIELD_NUMBER = 3;
      private int state_;
      /**
       * <code>int32 State = 3;</code>
       */
      public int getState() {
        return state_;
      }

      public static final int CHECKIN_FIELD_NUMBER = 4;
      private volatile Object checkIn_;
      /**
       * <code>string CheckIn = 4;</code>
       */
      public String getCheckIn() {
        Object ref = checkIn_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          checkIn_ = s;
          return s;
        }
      }
      /**
       * <code>string CheckIn = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCheckInBytes() {
        Object ref = checkIn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          checkIn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int CHECKOUT_FIELD_NUMBER = 5;
      private volatile Object checkOut_;
      /**
       * <code>string CheckOut = 5;</code>
       */
      public String getCheckOut() {
        Object ref = checkOut_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          checkOut_ = s;
          return s;
        }
      }
      /**
       * <code>string CheckOut = 5;</code>
       */
      public com.google.protobuf.ByteString
          getCheckOutBytes() {
        Object ref = checkOut_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          checkOut_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int CUSTOMERNAME_FIELD_NUMBER = 6;
      private volatile Object customerName_;
      /**
       * <code>string CustomerName = 6;</code>
       */
      public String getCustomerName() {
        Object ref = customerName_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          customerName_ = s;
          return s;
        }
      }
      /**
       * <code>string CustomerName = 6;</code>
       */
      public com.google.protobuf.ByteString
          getCustomerNameBytes() {
        Object ref = customerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          customerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getHotelMainIDBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hotelMainID_);
        }
        if (!getRoomNoBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, roomNo_);
        }
        if (state_ != 0) {
          output.writeInt32(3, state_);
        }
        if (!getCheckInBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 4, checkIn_);
        }
        if (!getCheckOutBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 5, checkOut_);
        }
        if (!getCustomerNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 6, customerName_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getHotelMainIDBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hotelMainID_);
        }
        if (!getRoomNoBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, roomNo_);
        }
        if (state_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, state_);
        }
        if (!getCheckInBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, checkIn_);
        }
        if (!getCheckOutBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, checkOut_);
        }
        if (!getCustomerNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, customerName_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof RoomStatusInfo)) {
          return super.equals(obj);
        }
        RoomStatusInfo other = (RoomStatusInfo) obj;

        boolean result = true;
        result = result && getHotelMainID()
            .equals(other.getHotelMainID());
        result = result && getRoomNo()
            .equals(other.getRoomNo());
        result = result && (getState()
            == other.getState());
        result = result && getCheckIn()
            .equals(other.getCheckIn());
        result = result && getCheckOut()
            .equals(other.getCheckOut());
        result = result && getCustomerName()
            .equals(other.getCustomerName());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + HOTELMAINID_FIELD_NUMBER;
        hash = (53 * hash) + getHotelMainID().hashCode();
        hash = (37 * hash) + ROOMNO_FIELD_NUMBER;
        hash = (53 * hash) + getRoomNo().hashCode();
        hash = (37 * hash) + STATE_FIELD_NUMBER;
        hash = (53 * hash) + getState();
        hash = (37 * hash) + CHECKIN_FIELD_NUMBER;
        hash = (53 * hash) + getCheckIn().hashCode();
        hash = (37 * hash) + CHECKOUT_FIELD_NUMBER;
        hash = (53 * hash) + getCheckOut().hashCode();
        hash = (37 * hash) + CUSTOMERNAME_FIELD_NUMBER;
        hash = (53 * hash) + getCustomerName().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static RoomStatusInfo parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static RoomStatusInfo parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static RoomStatusInfo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static RoomStatusInfo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static RoomStatusInfo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static RoomStatusInfo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static RoomStatusInfo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static RoomStatusInfo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static RoomStatusInfo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static RoomStatusInfo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static RoomStatusInfo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static RoomStatusInfo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(RoomStatusInfo prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo)
          RoomStatusInfoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return RoomStatusInfoLOuterClass.internal_static_study_springboot_myspringboot_model_protobuf_RoomStatusInfoL_RoomStatusInfo_descriptor;
        }

        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return RoomStatusInfoLOuterClass.internal_static_study_springboot_myspringboot_model_protobuf_RoomStatusInfoL_RoomStatusInfo_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  RoomStatusInfo.class, Builder.class);
        }

        // Construct using study.springboot.myspringboot.model.protobuf.RoomStatusInfoLOuterClass.RoomStatusInfoL.RoomStatusInfo.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          hotelMainID_ = "";

          roomNo_ = "";

          state_ = 0;

          checkIn_ = "";

          checkOut_ = "";

          customerName_ = "";

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return RoomStatusInfoLOuterClass.internal_static_study_springboot_myspringboot_model_protobuf_RoomStatusInfoL_RoomStatusInfo_descriptor;
        }

        public RoomStatusInfo getDefaultInstanceForType() {
          return RoomStatusInfo.getDefaultInstance();
        }

        public RoomStatusInfo build() {
          RoomStatusInfo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public RoomStatusInfo buildPartial() {
          RoomStatusInfo result = new RoomStatusInfo(this);
          result.hotelMainID_ = hotelMainID_;
          result.roomNo_ = roomNo_;
          result.state_ = state_;
          result.checkIn_ = checkIn_;
          result.checkOut_ = checkOut_;
          result.customerName_ = customerName_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof RoomStatusInfo) {
            return mergeFrom((RoomStatusInfo)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(RoomStatusInfo other) {
          if (other == RoomStatusInfo.getDefaultInstance()) return this;
          if (!other.getHotelMainID().isEmpty()) {
            hotelMainID_ = other.hotelMainID_;
            onChanged();
          }
          if (!other.getRoomNo().isEmpty()) {
            roomNo_ = other.roomNo_;
            onChanged();
          }
          if (other.getState() != 0) {
            setState(other.getState());
          }
          if (!other.getCheckIn().isEmpty()) {
            checkIn_ = other.checkIn_;
            onChanged();
          }
          if (!other.getCheckOut().isEmpty()) {
            checkOut_ = other.checkOut_;
            onChanged();
          }
          if (!other.getCustomerName().isEmpty()) {
            customerName_ = other.customerName_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          RoomStatusInfo parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (RoomStatusInfo) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private Object hotelMainID_ = "";
        /**
         * <code>string HotelMainID = 1;</code>
         */
        public String getHotelMainID() {
          Object ref = hotelMainID_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            hotelMainID_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>string HotelMainID = 1;</code>
         */
        public com.google.protobuf.ByteString
            getHotelMainIDBytes() {
          Object ref = hotelMainID_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            hotelMainID_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string HotelMainID = 1;</code>
         */
        public Builder setHotelMainID(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          hotelMainID_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string HotelMainID = 1;</code>
         */
        public Builder clearHotelMainID() {
          
          hotelMainID_ = getDefaultInstance().getHotelMainID();
          onChanged();
          return this;
        }
        /**
         * <code>string HotelMainID = 1;</code>
         */
        public Builder setHotelMainIDBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          hotelMainID_ = value;
          onChanged();
          return this;
        }

        private Object roomNo_ = "";
        /**
         * <code>string RoomNo = 2;</code>
         */
        public String getRoomNo() {
          Object ref = roomNo_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            roomNo_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>string RoomNo = 2;</code>
         */
        public com.google.protobuf.ByteString
            getRoomNoBytes() {
          Object ref = roomNo_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            roomNo_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string RoomNo = 2;</code>
         */
        public Builder setRoomNo(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          roomNo_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string RoomNo = 2;</code>
         */
        public Builder clearRoomNo() {
          
          roomNo_ = getDefaultInstance().getRoomNo();
          onChanged();
          return this;
        }
        /**
         * <code>string RoomNo = 2;</code>
         */
        public Builder setRoomNoBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          roomNo_ = value;
          onChanged();
          return this;
        }

        private int state_ ;
        /**
         * <code>int32 State = 3;</code>
         */
        public int getState() {
          return state_;
        }
        /**
         * <code>int32 State = 3;</code>
         */
        public Builder setState(int value) {
          
          state_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 State = 3;</code>
         */
        public Builder clearState() {
          
          state_ = 0;
          onChanged();
          return this;
        }

        private Object checkIn_ = "";
        /**
         * <code>string CheckIn = 4;</code>
         */
        public String getCheckIn() {
          Object ref = checkIn_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            checkIn_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>string CheckIn = 4;</code>
         */
        public com.google.protobuf.ByteString
            getCheckInBytes() {
          Object ref = checkIn_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            checkIn_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string CheckIn = 4;</code>
         */
        public Builder setCheckIn(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          checkIn_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string CheckIn = 4;</code>
         */
        public Builder clearCheckIn() {
          
          checkIn_ = getDefaultInstance().getCheckIn();
          onChanged();
          return this;
        }
        /**
         * <code>string CheckIn = 4;</code>
         */
        public Builder setCheckInBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          checkIn_ = value;
          onChanged();
          return this;
        }

        private Object checkOut_ = "";
        /**
         * <code>string CheckOut = 5;</code>
         */
        public String getCheckOut() {
          Object ref = checkOut_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            checkOut_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>string CheckOut = 5;</code>
         */
        public com.google.protobuf.ByteString
            getCheckOutBytes() {
          Object ref = checkOut_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            checkOut_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string CheckOut = 5;</code>
         */
        public Builder setCheckOut(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          checkOut_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string CheckOut = 5;</code>
         */
        public Builder clearCheckOut() {
          
          checkOut_ = getDefaultInstance().getCheckOut();
          onChanged();
          return this;
        }
        /**
         * <code>string CheckOut = 5;</code>
         */
        public Builder setCheckOutBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          checkOut_ = value;
          onChanged();
          return this;
        }

        private Object customerName_ = "";
        /**
         * <code>string CustomerName = 6;</code>
         */
        public String getCustomerName() {
          Object ref = customerName_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            customerName_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>string CustomerName = 6;</code>
         */
        public com.google.protobuf.ByteString
            getCustomerNameBytes() {
          Object ref = customerName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            customerName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string CustomerName = 6;</code>
         */
        public Builder setCustomerName(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          customerName_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string CustomerName = 6;</code>
         */
        public Builder clearCustomerName() {
          
          customerName_ = getDefaultInstance().getCustomerName();
          onChanged();
          return this;
        }
        /**
         * <code>string CustomerName = 6;</code>
         */
        public Builder setCustomerNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          customerName_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo)
      }

      // @@protoc_insertion_point(class_scope:study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo)
      private static final RoomStatusInfo DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new RoomStatusInfo();
      }

      public static RoomStatusInfo getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<RoomStatusInfo>
          PARSER = new com.google.protobuf.AbstractParser<RoomStatusInfo>() {
        public RoomStatusInfo parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new RoomStatusInfo(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<RoomStatusInfo> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<RoomStatusInfo> getParserForType() {
        return PARSER;
      }

      public RoomStatusInfo getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int ROOMSTATUSINFOLIST_FIELD_NUMBER = 1;
    private java.util.List<RoomStatusInfo> roomStatusInfoList_;
    /**
     * <code>repeated .study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo RoomStatusInfoList = 1;</code>
     */
    public java.util.List<RoomStatusInfo> getRoomStatusInfoListList() {
      return roomStatusInfoList_;
    }
    /**
     * <code>repeated .study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo RoomStatusInfoList = 1;</code>
     */
    public java.util.List<? extends RoomStatusInfoOrBuilder>
        getRoomStatusInfoListOrBuilderList() {
      return roomStatusInfoList_;
    }
    /**
     * <code>repeated .study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo RoomStatusInfoList = 1;</code>
     */
    public int getRoomStatusInfoListCount() {
      return roomStatusInfoList_.size();
    }
    /**
     * <code>repeated .study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo RoomStatusInfoList = 1;</code>
     */
    public RoomStatusInfo getRoomStatusInfoList(int index) {
      return roomStatusInfoList_.get(index);
    }
    /**
     * <code>repeated .study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo RoomStatusInfoList = 1;</code>
     */
    public RoomStatusInfoOrBuilder getRoomStatusInfoListOrBuilder(
        int index) {
      return roomStatusInfoList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < roomStatusInfoList_.size(); i++) {
        output.writeMessage(1, roomStatusInfoList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < roomStatusInfoList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, roomStatusInfoList_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RoomStatusInfoL)) {
        return super.equals(obj);
      }
      RoomStatusInfoL other = (RoomStatusInfoL) obj;

      boolean result = true;
      result = result && getRoomStatusInfoListList()
          .equals(other.getRoomStatusInfoListList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRoomStatusInfoListCount() > 0) {
        hash = (37 * hash) + ROOMSTATUSINFOLIST_FIELD_NUMBER;
        hash = (53 * hash) + getRoomStatusInfoListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RoomStatusInfoL parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RoomStatusInfoL parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RoomStatusInfoL parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RoomStatusInfoL parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RoomStatusInfoL parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RoomStatusInfoL parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RoomStatusInfoL parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RoomStatusInfoL parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RoomStatusInfoL parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RoomStatusInfoL parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RoomStatusInfoL parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RoomStatusInfoL parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RoomStatusInfoL prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code study.springboot.myspringboot.model.protobuf.RoomStatusInfoL}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:study.springboot.myspringboot.model.protobuf.RoomStatusInfoL)
        RoomStatusInfoLOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RoomStatusInfoLOuterClass.internal_static_study_springboot_myspringboot_model_protobuf_RoomStatusInfoL_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RoomStatusInfoLOuterClass.internal_static_study_springboot_myspringboot_model_protobuf_RoomStatusInfoL_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RoomStatusInfoL.class, Builder.class);
      }

      // Construct using study.springboot.myspringboot.model.protobuf.RoomStatusInfoLOuterClass.RoomStatusInfoL.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRoomStatusInfoListFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (roomStatusInfoListBuilder_ == null) {
          roomStatusInfoList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          roomStatusInfoListBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RoomStatusInfoLOuterClass.internal_static_study_springboot_myspringboot_model_protobuf_RoomStatusInfoL_descriptor;
      }

      public RoomStatusInfoL getDefaultInstanceForType() {
        return RoomStatusInfoL.getDefaultInstance();
      }

      public RoomStatusInfoL build() {
        RoomStatusInfoL result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public RoomStatusInfoL buildPartial() {
        RoomStatusInfoL result = new RoomStatusInfoL(this);
        int from_bitField0_ = bitField0_;
        if (roomStatusInfoListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            roomStatusInfoList_ = java.util.Collections.unmodifiableList(roomStatusInfoList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.roomStatusInfoList_ = roomStatusInfoList_;
        } else {
          result.roomStatusInfoList_ = roomStatusInfoListBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RoomStatusInfoL) {
          return mergeFrom((RoomStatusInfoL)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RoomStatusInfoL other) {
        if (other == RoomStatusInfoL.getDefaultInstance()) return this;
        if (roomStatusInfoListBuilder_ == null) {
          if (!other.roomStatusInfoList_.isEmpty()) {
            if (roomStatusInfoList_.isEmpty()) {
              roomStatusInfoList_ = other.roomStatusInfoList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRoomStatusInfoListIsMutable();
              roomStatusInfoList_.addAll(other.roomStatusInfoList_);
            }
            onChanged();
          }
        } else {
          if (!other.roomStatusInfoList_.isEmpty()) {
            if (roomStatusInfoListBuilder_.isEmpty()) {
              roomStatusInfoListBuilder_.dispose();
              roomStatusInfoListBuilder_ = null;
              roomStatusInfoList_ = other.roomStatusInfoList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              roomStatusInfoListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRoomStatusInfoListFieldBuilder() : null;
            } else {
              roomStatusInfoListBuilder_.addAllMessages(other.roomStatusInfoList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RoomStatusInfoL parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RoomStatusInfoL) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<RoomStatusInfo> roomStatusInfoList_ =
        java.util.Collections.emptyList();
      private void ensureRoomStatusInfoListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          roomStatusInfoList_ = new java.util.ArrayList<RoomStatusInfo>(roomStatusInfoList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          RoomStatusInfo, RoomStatusInfo.Builder, RoomStatusInfoOrBuilder> roomStatusInfoListBuilder_;

      /**
       * <code>repeated .study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo RoomStatusInfoList = 1;</code>
       */
      public java.util.List<RoomStatusInfo> getRoomStatusInfoListList() {
        if (roomStatusInfoListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(roomStatusInfoList_);
        } else {
          return roomStatusInfoListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo RoomStatusInfoList = 1;</code>
       */
      public int getRoomStatusInfoListCount() {
        if (roomStatusInfoListBuilder_ == null) {
          return roomStatusInfoList_.size();
        } else {
          return roomStatusInfoListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo RoomStatusInfoList = 1;</code>
       */
      public RoomStatusInfo getRoomStatusInfoList(int index) {
        if (roomStatusInfoListBuilder_ == null) {
          return roomStatusInfoList_.get(index);
        } else {
          return roomStatusInfoListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo RoomStatusInfoList = 1;</code>
       */
      public Builder setRoomStatusInfoList(
          int index, RoomStatusInfo value) {
        if (roomStatusInfoListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoomStatusInfoListIsMutable();
          roomStatusInfoList_.set(index, value);
          onChanged();
        } else {
          roomStatusInfoListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo RoomStatusInfoList = 1;</code>
       */
      public Builder setRoomStatusInfoList(
          int index, RoomStatusInfo.Builder builderForValue) {
        if (roomStatusInfoListBuilder_ == null) {
          ensureRoomStatusInfoListIsMutable();
          roomStatusInfoList_.set(index, builderForValue.build());
          onChanged();
        } else {
          roomStatusInfoListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo RoomStatusInfoList = 1;</code>
       */
      public Builder addRoomStatusInfoList(RoomStatusInfo value) {
        if (roomStatusInfoListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoomStatusInfoListIsMutable();
          roomStatusInfoList_.add(value);
          onChanged();
        } else {
          roomStatusInfoListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo RoomStatusInfoList = 1;</code>
       */
      public Builder addRoomStatusInfoList(
          int index, RoomStatusInfo value) {
        if (roomStatusInfoListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoomStatusInfoListIsMutable();
          roomStatusInfoList_.add(index, value);
          onChanged();
        } else {
          roomStatusInfoListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo RoomStatusInfoList = 1;</code>
       */
      public Builder addRoomStatusInfoList(
          RoomStatusInfo.Builder builderForValue) {
        if (roomStatusInfoListBuilder_ == null) {
          ensureRoomStatusInfoListIsMutable();
          roomStatusInfoList_.add(builderForValue.build());
          onChanged();
        } else {
          roomStatusInfoListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo RoomStatusInfoList = 1;</code>
       */
      public Builder addRoomStatusInfoList(
          int index, RoomStatusInfo.Builder builderForValue) {
        if (roomStatusInfoListBuilder_ == null) {
          ensureRoomStatusInfoListIsMutable();
          roomStatusInfoList_.add(index, builderForValue.build());
          onChanged();
        } else {
          roomStatusInfoListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo RoomStatusInfoList = 1;</code>
       */
      public Builder addAllRoomStatusInfoList(
          Iterable<? extends RoomStatusInfo> values) {
        if (roomStatusInfoListBuilder_ == null) {
          ensureRoomStatusInfoListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, roomStatusInfoList_);
          onChanged();
        } else {
          roomStatusInfoListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo RoomStatusInfoList = 1;</code>
       */
      public Builder clearRoomStatusInfoList() {
        if (roomStatusInfoListBuilder_ == null) {
          roomStatusInfoList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          roomStatusInfoListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo RoomStatusInfoList = 1;</code>
       */
      public Builder removeRoomStatusInfoList(int index) {
        if (roomStatusInfoListBuilder_ == null) {
          ensureRoomStatusInfoListIsMutable();
          roomStatusInfoList_.remove(index);
          onChanged();
        } else {
          roomStatusInfoListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo RoomStatusInfoList = 1;</code>
       */
      public RoomStatusInfo.Builder getRoomStatusInfoListBuilder(
          int index) {
        return getRoomStatusInfoListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo RoomStatusInfoList = 1;</code>
       */
      public RoomStatusInfoOrBuilder getRoomStatusInfoListOrBuilder(
          int index) {
        if (roomStatusInfoListBuilder_ == null) {
          return roomStatusInfoList_.get(index);  } else {
          return roomStatusInfoListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo RoomStatusInfoList = 1;</code>
       */
      public java.util.List<? extends RoomStatusInfoOrBuilder>
           getRoomStatusInfoListOrBuilderList() {
        if (roomStatusInfoListBuilder_ != null) {
          return roomStatusInfoListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(roomStatusInfoList_);
        }
      }
      /**
       * <code>repeated .study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo RoomStatusInfoList = 1;</code>
       */
      public RoomStatusInfo.Builder addRoomStatusInfoListBuilder() {
        return getRoomStatusInfoListFieldBuilder().addBuilder(
            RoomStatusInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo RoomStatusInfoList = 1;</code>
       */
      public RoomStatusInfo.Builder addRoomStatusInfoListBuilder(
          int index) {
        return getRoomStatusInfoListFieldBuilder().addBuilder(
            index, RoomStatusInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .study.springboot.myspringboot.model.protobuf.RoomStatusInfoL.RoomStatusInfo RoomStatusInfoList = 1;</code>
       */
      public java.util.List<RoomStatusInfo.Builder>
           getRoomStatusInfoListBuilderList() {
        return getRoomStatusInfoListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          RoomStatusInfo, RoomStatusInfo.Builder, RoomStatusInfoOrBuilder>
          getRoomStatusInfoListFieldBuilder() {
        if (roomStatusInfoListBuilder_ == null) {
          roomStatusInfoListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              RoomStatusInfo, RoomStatusInfo.Builder, RoomStatusInfoOrBuilder>(
                  roomStatusInfoList_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          roomStatusInfoList_ = null;
        }
        return roomStatusInfoListBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:study.springboot.myspringboot.model.protobuf.RoomStatusInfoL)
    }

    // @@protoc_insertion_point(class_scope:study.springboot.myspringboot.model.protobuf.RoomStatusInfoL)
    private static final RoomStatusInfoL DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RoomStatusInfoL();
    }

    public static RoomStatusInfoL getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoomStatusInfoL>
        PARSER = new com.google.protobuf.AbstractParser<RoomStatusInfoL>() {
      public RoomStatusInfoL parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RoomStatusInfoL(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RoomStatusInfoL> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RoomStatusInfoL> getParserForType() {
      return PARSER;
    }

    public RoomStatusInfoL getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_study_springboot_myspringboot_model_protobuf_RoomStatusInfoL_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_study_springboot_myspringboot_model_protobuf_RoomStatusInfoL_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_study_springboot_myspringboot_model_protobuf_RoomStatusInfoL_RoomStatusInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_study_springboot_myspringboot_model_protobuf_RoomStatusInfoL_RoomStatusInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025roomStatusInfoL.proto\022,study.springboo" +
      "t.myspringboot.model.protobuf\"\372\001\n\017RoomSt" +
      "atusInfoL\022h\n\022RoomStatusInfoList\030\001 \003(\0132L." +
      "study.springboot.myspringboot.model.prot" +
      "obuf.RoomStatusInfoL.RoomStatusInfo\032}\n\016R" +
      "oomStatusInfo\022\023\n\013HotelMainID\030\001 \001(\t\022\016\n\006Ro" +
      "omNo\030\002 \001(\t\022\r\n\005State\030\003 \001(\005\022\017\n\007CheckIn\030\004 \001" +
      "(\t\022\020\n\010CheckOut\030\005 \001(\t\022\024\n\014CustomerName\030\006 \001" +
      "(\tB.\n,study.springboot.myspringboot.mode" +
      "l.protobufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_study_springboot_myspringboot_model_protobuf_RoomStatusInfoL_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_study_springboot_myspringboot_model_protobuf_RoomStatusInfoL_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_study_springboot_myspringboot_model_protobuf_RoomStatusInfoL_descriptor,
        new String[] { "RoomStatusInfoList", });
    internal_static_study_springboot_myspringboot_model_protobuf_RoomStatusInfoL_RoomStatusInfo_descriptor =
      internal_static_study_springboot_myspringboot_model_protobuf_RoomStatusInfoL_descriptor.getNestedTypes().get(0);
    internal_static_study_springboot_myspringboot_model_protobuf_RoomStatusInfoL_RoomStatusInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_study_springboot_myspringboot_model_protobuf_RoomStatusInfoL_RoomStatusInfo_descriptor,
        new String[] { "HotelMainID", "RoomNo", "State", "CheckIn", "CheckOut", "CustomerName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
